@Ecommerce.Api_HostAddress = http://localhost:5164

### Create Product
POST {{Ecommerce.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "sku": "PROD-001",
  "name": "Sample Product",
  "price": 29.99,
  "categoryId": "550e8400-e29b-41d4-a716-446655440000",
  "description": "A sample product for testing",
  "currency": "USD"
}

### Get Products (paged)
GET {{Ecommerce.Api_HostAddress}}/api/products?pageNumber=1&pageSize=20
Accept: application/json


### Get Product By Id
GET {{Ecommerce.Api_HostAddress}}/api/products/3871FA99-7917-487F-9E30-24943B37453B
Accept: application/json


### Update Product
PUT {{Ecommerce.Api_HostAddress}}/api/products/3871FA99-7917-487F-9E30-24943B37453B
Content-Type: application/json

{
  "name": "Updated Product Name",
  "description": "Updated description for the product",
  "price": 39.99,
  "currency": "USD",
  "categoryId": "550e8400-e29b-41d4-a716-446655440000",
  "isActive": true
}
